// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/credential_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/credential_repo.go -destination=internal/mocks/mock_credential_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/safrizal997/travapp-auth-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialRepository is a mock of CredentialRepository interface.
type MockCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialRepositoryMockRecorder is the mock recorder for MockCredentialRepository.
type MockCredentialRepositoryMockRecorder struct {
	mock *MockCredentialRepository
}

// NewMockCredentialRepository creates a new mock instance.
func NewMockCredentialRepository(ctrl *gomock.Controller) *MockCredentialRepository {
	mock := &MockCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialRepository) EXPECT() *MockCredentialRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCredentialRepository) Create(ctx context.Context, cred *entity.AuthCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCredentialRepositoryMockRecorder) Create(ctx, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCredentialRepository)(nil).Create), ctx, cred)
}

// GetByEmailAndTenant mocks base method.
func (m *MockCredentialRepository) GetByEmailAndTenant(ctx context.Context, email string, tenantID uuid.UUID, provider string) (*entity.AuthCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmailAndTenant", ctx, email, tenantID, provider)
	ret0, _ := ret[0].(*entity.AuthCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmailAndTenant indicates an expected call of GetByEmailAndTenant.
func (mr *MockCredentialRepositoryMockRecorder) GetByEmailAndTenant(ctx, email, tenantID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmailAndTenant", reflect.TypeOf((*MockCredentialRepository)(nil).GetByEmailAndTenant), ctx, email, tenantID, provider)
}

// GetByID mocks base method.
func (m *MockCredentialRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.AuthCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.AuthCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCredentialRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCredentialRepository)(nil).GetByID), ctx, id)
}

// GetByProviderID mocks base method.
func (m *MockCredentialRepository) GetByProviderID(ctx context.Context, providerID, provider string, tenantID uuid.UUID) (*entity.AuthCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProviderID", ctx, providerID, provider, tenantID)
	ret0, _ := ret[0].(*entity.AuthCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProviderID indicates an expected call of GetByProviderID.
func (mr *MockCredentialRepositoryMockRecorder) GetByProviderID(ctx, providerID, provider, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProviderID", reflect.TypeOf((*MockCredentialRepository)(nil).GetByProviderID), ctx, providerID, provider, tenantID)
}

// ResetFailedAttempts mocks base method.
func (m *MockCredentialRepository) ResetFailedAttempts(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailedAttempts", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetFailedAttempts indicates an expected call of ResetFailedAttempts.
func (mr *MockCredentialRepositoryMockRecorder) ResetFailedAttempts(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailedAttempts", reflect.TypeOf((*MockCredentialRepository)(nil).ResetFailedAttempts), ctx, id)
}

// UpdateFailedAttempts mocks base method.
func (m *MockCredentialRepository) UpdateFailedAttempts(ctx context.Context, id uuid.UUID, attempts int, lockedUntil *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFailedAttempts", ctx, id, attempts, lockedUntil)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFailedAttempts indicates an expected call of UpdateFailedAttempts.
func (mr *MockCredentialRepositoryMockRecorder) UpdateFailedAttempts(ctx, id, attempts, lockedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFailedAttempts", reflect.TypeOf((*MockCredentialRepository)(nil).UpdateFailedAttempts), ctx, id, attempts, lockedUntil)
}

// UpdateIsActive mocks base method.
func (m *MockCredentialRepository) UpdateIsActive(ctx context.Context, id uuid.UUID, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIsActive", ctx, id, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIsActive indicates an expected call of UpdateIsActive.
func (mr *MockCredentialRepositoryMockRecorder) UpdateIsActive(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIsActive", reflect.TypeOf((*MockCredentialRepository)(nil).UpdateIsActive), ctx, id, isActive)
}

// UpdateLastLogin mocks base method.
func (m *MockCredentialRepository) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockCredentialRepositoryMockRecorder) UpdateLastLogin(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockCredentialRepository)(nil).UpdateLastLogin), ctx, id)
}

// UpdatePassword mocks base method.
func (m *MockCredentialRepository) UpdatePassword(ctx context.Context, id uuid.UUID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, id, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockCredentialRepositoryMockRecorder) UpdatePassword(ctx, id, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockCredentialRepository)(nil).UpdatePassword), ctx, id, passwordHash)
}

// VerifyEmail mocks base method.
func (m *MockCredentialRepository) VerifyEmail(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockCredentialRepositoryMockRecorder) VerifyEmail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockCredentialRepository)(nil).VerifyEmail), ctx, id)
}
