// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/tenant_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/tenant_repo.go -destination=internal/mocks/mock_tenant_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/safrizal997/travapp-auth-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// GetActiveTenant mocks base method.
func (m *MockTenantRepository) GetActiveTenant(ctx context.Context, id uuid.UUID) (*entity.AuthTenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveTenant", ctx, id)
	ret0, _ := ret[0].(*entity.AuthTenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveTenant indicates an expected call of GetActiveTenant.
func (mr *MockTenantRepositoryMockRecorder) GetActiveTenant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveTenant", reflect.TypeOf((*MockTenantRepository)(nil).GetActiveTenant), ctx, id)
}

// GetByCode mocks base method.
func (m *MockTenantRepository) GetByCode(ctx context.Context, code string) (*entity.AuthTenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*entity.AuthTenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockTenantRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockTenantRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockTenantRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.AuthTenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.AuthTenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTenantRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTenantRepository)(nil).GetByID), ctx, id)
}
