// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/token_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/token_repo.go -destination=internal/mocks/mock_token_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	repository "github.com/safrizal997/travapp-auth-service/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// BlacklistAccessToken mocks base method.
func (m *MockTokenRepository) BlacklistAccessToken(ctx context.Context, jti string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlacklistAccessToken", ctx, jti, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlacklistAccessToken indicates an expected call of BlacklistAccessToken.
func (mr *MockTokenRepositoryMockRecorder) BlacklistAccessToken(ctx, jti, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlacklistAccessToken", reflect.TypeOf((*MockTokenRepository)(nil).BlacklistAccessToken), ctx, jti, ttl)
}

// DeleteAllRefreshTokens mocks base method.
func (m *MockTokenRepository) DeleteAllRefreshTokens(ctx context.Context, credentialID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllRefreshTokens", ctx, credentialID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllRefreshTokens indicates an expected call of DeleteAllRefreshTokens.
func (mr *MockTokenRepositoryMockRecorder) DeleteAllRefreshTokens(ctx, credentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllRefreshTokens", reflect.TypeOf((*MockTokenRepository)(nil).DeleteAllRefreshTokens), ctx, credentialID)
}

// DeleteOAuthState mocks base method.
func (m *MockTokenRepository) DeleteOAuthState(ctx context.Context, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOAuthState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOAuthState indicates an expected call of DeleteOAuthState.
func (mr *MockTokenRepositoryMockRecorder) DeleteOAuthState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOAuthState", reflect.TypeOf((*MockTokenRepository)(nil).DeleteOAuthState), ctx, state)
}

// DeleteRefreshToken mocks base method.
func (m *MockTokenRepository) DeleteRefreshToken(ctx context.Context, credentialID uuid.UUID, jti string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, credentialID, jti)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockTokenRepositoryMockRecorder) DeleteRefreshToken(ctx, credentialID, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockTokenRepository)(nil).DeleteRefreshToken), ctx, credentialID, jti)
}

// DeleteRefreshTokenFamily mocks base method.
func (m *MockTokenRepository) DeleteRefreshTokenFamily(ctx context.Context, familyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshTokenFamily", ctx, familyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshTokenFamily indicates an expected call of DeleteRefreshTokenFamily.
func (mr *MockTokenRepositoryMockRecorder) DeleteRefreshTokenFamily(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshTokenFamily", reflect.TypeOf((*MockTokenRepository)(nil).DeleteRefreshTokenFamily), ctx, familyID)
}

// FindRefreshTokenByHash mocks base method.
func (m *MockTokenRepository) FindRefreshTokenByHash(ctx context.Context, tokenHash string) (*repository.RefreshTokenData, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRefreshTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(*repository.RefreshTokenData)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// FindRefreshTokenByHash indicates an expected call of FindRefreshTokenByHash.
func (mr *MockTokenRepositoryMockRecorder) FindRefreshTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRefreshTokenByHash", reflect.TypeOf((*MockTokenRepository)(nil).FindRefreshTokenByHash), ctx, tokenHash)
}

// GetOAuthState mocks base method.
func (m *MockTokenRepository) GetOAuthState(ctx context.Context, state string) (*repository.OAuthStateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthState", ctx, state)
	ret0, _ := ret[0].(*repository.OAuthStateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthState indicates an expected call of GetOAuthState.
func (mr *MockTokenRepositoryMockRecorder) GetOAuthState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthState", reflect.TypeOf((*MockTokenRepository)(nil).GetOAuthState), ctx, state)
}

// GetRBACCache mocks base method.
func (m *MockTokenRepository) GetRBACCache(ctx context.Context, credentialID uuid.UUID) (string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRBACCache", ctx, credentialID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRBACCache indicates an expected call of GetRBACCache.
func (mr *MockTokenRepositoryMockRecorder) GetRBACCache(ctx, credentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRBACCache", reflect.TypeOf((*MockTokenRepository)(nil).GetRBACCache), ctx, credentialID)
}

// GetRateLimit mocks base method.
func (m *MockTokenRepository) GetRateLimit(ctx context.Context, key string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRateLimit", ctx, key)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRateLimit indicates an expected call of GetRateLimit.
func (mr *MockTokenRepositoryMockRecorder) GetRateLimit(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRateLimit", reflect.TypeOf((*MockTokenRepository)(nil).GetRateLimit), ctx, key)
}

// GetRefreshToken mocks base method.
func (m *MockTokenRepository) GetRefreshToken(ctx context.Context, credentialID uuid.UUID, jti string) (*repository.RefreshTokenData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, credentialID, jti)
	ret0, _ := ret[0].(*repository.RefreshTokenData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockTokenRepositoryMockRecorder) GetRefreshToken(ctx, credentialID, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockTokenRepository)(nil).GetRefreshToken), ctx, credentialID, jti)
}

// IncrementRateLimit mocks base method.
func (m *MockTokenRepository) IncrementRateLimit(ctx context.Context, key string, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRateLimit", ctx, key, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementRateLimit indicates an expected call of IncrementRateLimit.
func (mr *MockTokenRepositoryMockRecorder) IncrementRateLimit(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRateLimit", reflect.TypeOf((*MockTokenRepository)(nil).IncrementRateLimit), ctx, key, ttl)
}

// IsAccessTokenBlacklisted mocks base method.
func (m *MockTokenRepository) IsAccessTokenBlacklisted(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAccessTokenBlacklisted", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAccessTokenBlacklisted indicates an expected call of IsAccessTokenBlacklisted.
func (mr *MockTokenRepositoryMockRecorder) IsAccessTokenBlacklisted(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAccessTokenBlacklisted", reflect.TypeOf((*MockTokenRepository)(nil).IsAccessTokenBlacklisted), ctx, jti)
}

// StoreOAuthState mocks base method.
func (m *MockTokenRepository) StoreOAuthState(ctx context.Context, state string, data *repository.OAuthStateData, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreOAuthState", ctx, state, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreOAuthState indicates an expected call of StoreOAuthState.
func (mr *MockTokenRepositoryMockRecorder) StoreOAuthState(ctx, state, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreOAuthState", reflect.TypeOf((*MockTokenRepository)(nil).StoreOAuthState), ctx, state, data, ttl)
}

// StoreRBACCache mocks base method.
func (m *MockTokenRepository) StoreRBACCache(ctx context.Context, credentialID uuid.UUID, role string, permissions []string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRBACCache", ctx, credentialID, role, permissions, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRBACCache indicates an expected call of StoreRBACCache.
func (mr *MockTokenRepositoryMockRecorder) StoreRBACCache(ctx, credentialID, role, permissions, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRBACCache", reflect.TypeOf((*MockTokenRepository)(nil).StoreRBACCache), ctx, credentialID, role, permissions, ttl)
}

// StoreRefreshToken mocks base method.
func (m *MockTokenRepository) StoreRefreshToken(ctx context.Context, credentialID uuid.UUID, jti string, data *repository.RefreshTokenData, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefreshToken", ctx, credentialID, jti, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefreshToken indicates an expected call of StoreRefreshToken.
func (mr *MockTokenRepositoryMockRecorder) StoreRefreshToken(ctx, credentialID, jti, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefreshToken", reflect.TypeOf((*MockTokenRepository)(nil).StoreRefreshToken), ctx, credentialID, jti, data, ttl)
}
