// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/safrizal997/travapp-auth-service/internal/usecase (interfaces: EmailVerificationStore)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_email_verification_store.go -package=mocks github.com/safrizal997/travapp-auth-service/internal/usecase EmailVerificationStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/safrizal997/travapp-auth-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailVerificationStore is a mock of EmailVerificationStore interface.
type MockEmailVerificationStore struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationStoreMockRecorder
	isgomock struct{}
}

// MockEmailVerificationStoreMockRecorder is the mock recorder for MockEmailVerificationStore.
type MockEmailVerificationStoreMockRecorder struct {
	mock *MockEmailVerificationStore
}

// NewMockEmailVerificationStore creates a new mock instance.
func NewMockEmailVerificationStore(ctrl *gomock.Controller) *MockEmailVerificationStore {
	mock := &MockEmailVerificationStore{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationStore) EXPECT() *MockEmailVerificationStoreMockRecorder {
	return m.recorder
}

// CreateEmailVerification mocks base method.
func (m *MockEmailVerificationStore) CreateEmailVerification(ctx context.Context, ev *entity.AuthEmailVerification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailVerification", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEmailVerification indicates an expected call of CreateEmailVerification.
func (mr *MockEmailVerificationStoreMockRecorder) CreateEmailVerification(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailVerification", reflect.TypeOf((*MockEmailVerificationStore)(nil).CreateEmailVerification), ctx, ev)
}
