// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/login_history_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/login_history_repo.go -destination=internal/mocks/mock_login_history_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/safrizal997/travapp-auth-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginHistoryRepository is a mock of LoginHistoryRepository interface.
type MockLoginHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoginHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockLoginHistoryRepositoryMockRecorder is the mock recorder for MockLoginHistoryRepository.
type MockLoginHistoryRepositoryMockRecorder struct {
	mock *MockLoginHistoryRepository
}

// NewMockLoginHistoryRepository creates a new mock instance.
func NewMockLoginHistoryRepository(ctrl *gomock.Controller) *MockLoginHistoryRepository {
	mock := &MockLoginHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockLoginHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginHistoryRepository) EXPECT() *MockLoginHistoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLoginHistoryRepository) Create(ctx context.Context, history *entity.AuthLoginHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLoginHistoryRepositoryMockRecorder) Create(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLoginHistoryRepository)(nil).Create), ctx, history)
}
