// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/safrizal997/travapp-auth-service/internal/usecase (interfaces: PasswordResetStore)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_password_reset_store.go -package=mocks github.com/safrizal997/travapp-auth-service/internal/usecase PasswordResetStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/safrizal997/travapp-auth-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordResetStore is a mock of PasswordResetStore interface.
type MockPasswordResetStore struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetStoreMockRecorder
	isgomock struct{}
}

// MockPasswordResetStoreMockRecorder is the mock recorder for MockPasswordResetStore.
type MockPasswordResetStoreMockRecorder struct {
	mock *MockPasswordResetStore
}

// NewMockPasswordResetStore creates a new mock instance.
func NewMockPasswordResetStore(ctrl *gomock.Controller) *MockPasswordResetStore {
	mock := &MockPasswordResetStore{ctrl: ctrl}
	mock.recorder = &MockPasswordResetStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetStore) EXPECT() *MockPasswordResetStoreMockRecorder {
	return m.recorder
}

// CreateEmailVerification mocks base method.
func (m *MockPasswordResetStore) CreateEmailVerification(ctx context.Context, ev *entity.AuthEmailVerification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailVerification", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEmailVerification indicates an expected call of CreateEmailVerification.
func (mr *MockPasswordResetStoreMockRecorder) CreateEmailVerification(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailVerification", reflect.TypeOf((*MockPasswordResetStore)(nil).CreateEmailVerification), ctx, ev)
}

// CreatePasswordReset mocks base method.
func (m *MockPasswordResetStore) CreatePasswordReset(ctx context.Context, reset *entity.AuthPasswordReset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePasswordReset", ctx, reset)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePasswordReset indicates an expected call of CreatePasswordReset.
func (mr *MockPasswordResetStoreMockRecorder) CreatePasswordReset(ctx, reset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePasswordReset", reflect.TypeOf((*MockPasswordResetStore)(nil).CreatePasswordReset), ctx, reset)
}

// GetEmailVerificationByToken mocks base method.
func (m *MockPasswordResetStore) GetEmailVerificationByToken(ctx context.Context, tokenHash string) (*entity.AuthEmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailVerificationByToken", ctx, tokenHash)
	ret0, _ := ret[0].(*entity.AuthEmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailVerificationByToken indicates an expected call of GetEmailVerificationByToken.
func (mr *MockPasswordResetStoreMockRecorder) GetEmailVerificationByToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailVerificationByToken", reflect.TypeOf((*MockPasswordResetStore)(nil).GetEmailVerificationByToken), ctx, tokenHash)
}

// GetPasswordResetByToken mocks base method.
func (m *MockPasswordResetStore) GetPasswordResetByToken(ctx context.Context, tokenHash string) (*entity.AuthPasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordResetByToken", ctx, tokenHash)
	ret0, _ := ret[0].(*entity.AuthPasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordResetByToken indicates an expected call of GetPasswordResetByToken.
func (mr *MockPasswordResetStoreMockRecorder) GetPasswordResetByToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordResetByToken", reflect.TypeOf((*MockPasswordResetStore)(nil).GetPasswordResetByToken), ctx, tokenHash)
}

// MarkEmailVerified mocks base method.
func (m *MockPasswordResetStore) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailVerified", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailVerified indicates an expected call of MarkEmailVerified.
func (mr *MockPasswordResetStoreMockRecorder) MarkEmailVerified(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailVerified", reflect.TypeOf((*MockPasswordResetStore)(nil).MarkEmailVerified), ctx, id)
}

// MarkPasswordResetUsed mocks base method.
func (m *MockPasswordResetStore) MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPasswordResetUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPasswordResetUsed indicates an expected call of MarkPasswordResetUsed.
func (mr *MockPasswordResetStoreMockRecorder) MarkPasswordResetUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPasswordResetUsed", reflect.TypeOf((*MockPasswordResetStore)(nil).MarkPasswordResetUsed), ctx, id)
}
