// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/role_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/role_repo.go -destination=internal/mocks/mock_role_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/safrizal997/travapp-auth-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// AssignRole mocks base method.
func (m *MockRoleRepository) AssignRole(ctx context.Context, assignment *entity.AuthRoleAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockRoleRepositoryMockRecorder) AssignRole(ctx, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockRoleRepository)(nil).AssignRole), ctx, assignment)
}

// GetByCodeAndTenant mocks base method.
func (m *MockRoleRepository) GetByCodeAndTenant(ctx context.Context, code string, tenantID uuid.UUID) (*entity.AuthRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCodeAndTenant", ctx, code, tenantID)
	ret0, _ := ret[0].(*entity.AuthRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCodeAndTenant indicates an expected call of GetByCodeAndTenant.
func (mr *MockRoleRepositoryMockRecorder) GetByCodeAndTenant(ctx, code, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCodeAndTenant", reflect.TypeOf((*MockRoleRepository)(nil).GetByCodeAndTenant), ctx, code, tenantID)
}

// GetDefaultRole mocks base method.
func (m *MockRoleRepository) GetDefaultRole(ctx context.Context, tenantID uuid.UUID) (*entity.AuthRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultRole", ctx, tenantID)
	ret0, _ := ret[0].(*entity.AuthRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultRole indicates an expected call of GetDefaultRole.
func (mr *MockRoleRepositoryMockRecorder) GetDefaultRole(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultRole", reflect.TypeOf((*MockRoleRepository)(nil).GetDefaultRole), ctx, tenantID)
}

// GetRoleAssignment mocks base method.
func (m *MockRoleRepository) GetRoleAssignment(ctx context.Context, credentialID, tenantID uuid.UUID) (*entity.AuthRoleAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleAssignment", ctx, credentialID, tenantID)
	ret0, _ := ret[0].(*entity.AuthRoleAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleAssignment indicates an expected call of GetRoleAssignment.
func (mr *MockRoleRepositoryMockRecorder) GetRoleAssignment(ctx, credentialID, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleAssignment", reflect.TypeOf((*MockRoleRepository)(nil).GetRoleAssignment), ctx, credentialID, tenantID)
}

// GetRoleWithPermissions mocks base method.
func (m *MockRoleRepository) GetRoleWithPermissions(ctx context.Context, credentialID, tenantID uuid.UUID) (*entity.AuthRole, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleWithPermissions", ctx, credentialID, tenantID)
	ret0, _ := ret[0].(*entity.AuthRole)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRoleWithPermissions indicates an expected call of GetRoleWithPermissions.
func (mr *MockRoleRepositoryMockRecorder) GetRoleWithPermissions(ctx, credentialID, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleWithPermissions", reflect.TypeOf((*MockRoleRepository)(nil).GetRoleWithPermissions), ctx, credentialID, tenantID)
}
